version: "3.8"
services:
  mysqldb:
    env_file:
      - .env
    image:
      mysql:5.7.8
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQLDB_DATABASE}"
    ports:
      - "${MYSQLDB_PORT}:${MYSQLDB_DOCKER_PORT}"
    volumes:
      - db:/var/lib/mysql
      - .m2:/root/.m2
    container_name: mysqldb_container
  backend:
    env_file:
      - .env
    depends_on:
      - mysqldb
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - "${JOBRUNR_DASHBOARD_PORT}:${JOBRUNR_DASHBOARD_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?createDatabaseIfNotExist=true&useSSL=true",
        "spring.datasource.username": "${MYSQLDB_ROOT_NAME}",
        "spring.datasource.password": "${MYSQLDB_ROOT_PASSWORD}"
      }'
    volumes:
      - ./backend:/backend
    container_name: backend_container
  frontend:
    env_file:
      - .env
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    container_name: frontend_container
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
volumes:
  db: